/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 3.4.0.0
 */
using System.Collections.Generic;
using Hime.Redist;
using Hime.Redist.Parsers;

namespace Lingu.Bootstrap
{
	/// <summary>
	/// Represents a parser
	/// </summary>
	public class LinguParser : LRkParser
	{
		/// <summary>
		/// The automaton for this parser
		/// </summary>
		private static readonly LRkAutomaton commonAutomaton = LRkAutomaton.Find(typeof(LinguParser), "LinguParser.bin");
		/// <summary>
		/// Contains the constant IDs for the variables and virtuals in this parser
		/// </summary>
		public class ID
		{
			/// <summary>
			/// The unique identifier for variable file
			/// </summary>
			public const int VariableFile = 0x0013;
			/// <summary>
			/// The unique identifier for variable cf_grammar
			/// </summary>
			public const int VariableCfGrammar = 0x0014;
			/// <summary>
			/// The unique identifier for variable grammar_options
			/// </summary>
			public const int VariableGrammarOptions = 0x0015;
			/// <summary>
			/// The unique identifier for variable option
			/// </summary>
			public const int VariableOption = 0x0016;
			/// <summary>
			/// The unique identifier for variable grammar_terminals
			/// </summary>
			public const int VariableGrammarTerminals = 0x0017;
			/// <summary>
			/// The unique identifier for variable terminal_item
			/// </summary>
			public const int VariableTerminalItem = 0x0018;
			/// <summary>
			/// The unique identifier for variable terminal_rule
			/// </summary>
			public const int VariableTerminalRule = 0x0019;
			/// <summary>
			/// The unique identifier for variable terminal_fragment
			/// </summary>
			public const int VariableTerminalFragment = 0x001A;
			/// <summary>
			/// The unique identifier for variable terminal_context
			/// </summary>
			public const int VariableTerminalContext = 0x001B;
			/// <summary>
			/// The unique identifier for variable terminal_definition
			/// </summary>
			public const int VariableTerminalDefinition = 0x001C;
			/// <summary>
			/// The unique identifier for variable terminal_difference
			/// </summary>
			public const int VariableTerminalDifference = 0x001D;
			/// <summary>
			/// The unique identifier for variable terminal_sequence
			/// </summary>
			public const int VariableTerminalSequence = 0x001E;
			/// <summary>
			/// The unique identifier for variable terminal_repetition
			/// </summary>
			public const int VariableTerminalRepetition = 0x001F;
			/// <summary>
			/// The unique identifier for variable terminal_element
			/// </summary>
			public const int VariableTerminalElement = 0x0020;
			/// <summary>
			/// The unique identifier for variable terminal_atom
			/// </summary>
			public const int VariableTerminalAtom = 0x0021;
			/// <summary>
			/// The unique identifier for variable terminal_range
			/// </summary>
			public const int VariableTerminalRange = 0x0022;
			/// <summary>
			/// The unique identifier for variable terminal_text
			/// </summary>
			public const int VariableTerminalText = 0x0023;
			/// <summary>
			/// The unique identifier for variable terminal_cardinalilty
			/// </summary>
			public const int VariableTerminalCardinalilty = 0x0024;
			/// <summary>
			/// The unique identifier for variable grammar_rules
			/// </summary>
			public const int VariableGrammarRules = 0x0025;
			/// <summary>
			/// The unique identifier for variable rule
			/// </summary>
			public const int VariableRule = 0x0026;
			/// <summary>
			/// The unique identifier for variable rule_simple
			/// </summary>
			public const int VariableRuleSimple = 0x0027;
			/// <summary>
			/// The unique identifier for variable rule_template
			/// </summary>
			public const int VariableRuleTemplate = 0x0028;
			/// <summary>
			/// The unique identifier for variable rule_definition
			/// </summary>
			public const int VariableRuleDefinition = 0x0029;
			/// <summary>
			/// The unique identifier for variable rule_alternative
			/// </summary>
			public const int VariableRuleAlternative = 0x002A;
			/// <summary>
			/// The unique identifier for variable rule_sequence
			/// </summary>
			public const int VariableRuleSequence = 0x002B;
			/// <summary>
			/// The unique identifier for variable rule_repetition
			/// </summary>
			public const int VariableRuleRepetition = 0x002C;
			/// <summary>
			/// The unique identifier for variable rule_tree_action
			/// </summary>
			public const int VariableRuleTreeAction = 0x002D;
			/// <summary>
			/// The unique identifier for variable rule_element
			/// </summary>
			public const int VariableRuleElement = 0x002E;
			/// <summary>
			/// The unique identifier for variable rule_atom
			/// </summary>
			public const int VariableRuleAtom = 0x002F;
			/// <summary>
			/// The unique identifier for variable rule_text
			/// </summary>
			public const int VariableRuleText = 0x0030;
			/// <summary>
			/// The unique identifier for variable rule_cardinality
			/// </summary>
			public const int VariableRuleCardinality = 0x0031;
			/// <summary>
			/// The unique identifier for variable rule_context
			/// </summary>
			public const int VariableRuleContext = 0x0032;
			/// <summary>
			/// The unique identifier for variable rule_sub
			/// </summary>
			public const int VariableRuleSub = 0x0033;
			/// <summary>
			/// The unique identifier for variable rule_action
			/// </summary>
			public const int VariableRuleAction = 0x0034;
			/// <summary>
			/// The unique identifier for variable rule_virtual
			/// </summary>
			public const int VariableRuleVirtual = 0x0035;
			/// <summary>
			/// The unique identifier for variable rule_ref
			/// </summary>
			public const int VariableRuleRef = 0x0036;
			/// <summary>
			/// The unique identifier for variable rule_ref_template
			/// </summary>
			public const int VariableRuleRefTemplate = 0x0037;
			/// <summary>
			/// The unique identifier for variable rule_arguments
			/// </summary>
			public const int VariableRuleArguments = 0x0038;
			/// <summary>
			/// The unique identifier for variable rule_params
			/// </summary>
			public const int VariableRuleParams = 0x0039;
			/// <summary>
			/// The unique identifier for virtual range
			/// </summary>
			public const int VirtualRange = 0x0052;
		}
		/// <summary>
		/// The collection of variables matched by this parser
		/// </summary>
		/// <remarks>
		/// The variables are in an order consistent with the automaton,
		/// so that variable indices in the automaton can be used to retrieve the variables in this table
		/// </remarks>
		private static readonly Symbol[] variables = {
			new Symbol(0x0013, "file"), 
			new Symbol(0x0014, "cf_grammar"), 
			new Symbol(0x0015, "grammar_options"), 
			new Symbol(0x0016, "option"), 
			new Symbol(0x0017, "grammar_terminals"), 
			new Symbol(0x0018, "terminal_item"), 
			new Symbol(0x0019, "terminal_rule"), 
			new Symbol(0x001A, "terminal_fragment"), 
			new Symbol(0x001B, "terminal_context"), 
			new Symbol(0x001C, "terminal_definition"), 
			new Symbol(0x001D, "terminal_difference"), 
			new Symbol(0x001E, "terminal_sequence"), 
			new Symbol(0x001F, "terminal_repetition"), 
			new Symbol(0x0020, "terminal_element"), 
			new Symbol(0x0021, "terminal_atom"), 
			new Symbol(0x0022, "terminal_range"), 
			new Symbol(0x0023, "terminal_text"), 
			new Symbol(0x0024, "terminal_cardinalilty"), 
			new Symbol(0x0025, "grammar_rules"), 
			new Symbol(0x0026, "rule"), 
			new Symbol(0x0027, "rule_simple"), 
			new Symbol(0x0028, "rule_template"), 
			new Symbol(0x0029, "rule_definition"), 
			new Symbol(0x002A, "rule_alternative"), 
			new Symbol(0x002B, "rule_sequence"), 
			new Symbol(0x002C, "rule_repetition"), 
			new Symbol(0x002D, "rule_tree_action"), 
			new Symbol(0x002E, "rule_element"), 
			new Symbol(0x002F, "rule_atom"), 
			new Symbol(0x0030, "rule_text"), 
			new Symbol(0x0031, "rule_cardinality"), 
			new Symbol(0x0032, "rule_context"), 
			new Symbol(0x0033, "rule_sub"), 
			new Symbol(0x0034, "rule_action"), 
			new Symbol(0x0035, "rule_virtual"), 
			new Symbol(0x0036, "rule_ref"), 
			new Symbol(0x0037, "rule_ref_template"), 
			new Symbol(0x0038, "rule_arguments"), 
			new Symbol(0x0039, "rule_params"), 
			new Symbol(0x003E, "__V62"), 
			new Symbol(0x0042, "__V66"), 
			new Symbol(0x0046, "__V70"), 
			new Symbol(0x0048, "__V72"), 
			new Symbol(0x004A, "__V74"), 
			new Symbol(0x004B, "__V75"), 
			new Symbol(0x0055, "__V85"), 
			new Symbol(0x0056, "__V86"), 
			new Symbol(0x0057, "__V87"), 
			new Symbol(0x005D, "__V93"), 
			new Symbol(0x005F, "__V95"), 
			new Symbol(0x0060, "__VAxiom") };
		/// <summary>
		/// The collection of virtuals matched by this parser
		/// </summary>
		/// <remarks>
		/// The virtuals are in an order consistent with the automaton,
		/// so that virtual indices in the automaton can be used to retrieve the virtuals in this table
		/// </remarks>
		private static readonly Symbol[] virtuals = {
			new Symbol(0x0052, "range") };
		/// <summary>
		/// Initializes a new instance of the parser
		/// </summary>
		/// <param name="lexer">The input lexer</param>
		public LinguParser(LinguLexer lexer) : base (commonAutomaton, variables, virtuals, null, lexer) { }

		/// <summary>
		/// Visitor interface
		/// </summary>
		public class Visitor
		{
			public virtual void OnTerminalSeparator(ASTNode node) {}
			public virtual void OnTerminalName(ASTNode node) {}
			public virtual void OnTerminalInteger(ASTNode node) {}
			public virtual void OnTerminalLiteralString(ASTNode node) {}
			public virtual void OnTerminalLiteralAny(ASTNode node) {}
			public virtual void OnTerminalLiteralText(ASTNode node) {}
			public virtual void OnTerminalLiteralClass(ASTNode node) {}
			public virtual void OnTerminalUnicodeBlock(ASTNode node) {}
			public virtual void OnTerminalUnicodeCategory(ASTNode node) {}
			public virtual void OnTerminalUnicodeCodepoint(ASTNode node) {}
			public virtual void OnVariableFile(ASTNode node) {}
			public virtual void OnVariableCfGrammar(ASTNode node) {}
			public virtual void OnVariableGrammarOptions(ASTNode node) {}
			public virtual void OnVariableOption(ASTNode node) {}
			public virtual void OnVariableGrammarTerminals(ASTNode node) {}
			public virtual void OnVariableTerminalItem(ASTNode node) {}
			public virtual void OnVariableTerminalRule(ASTNode node) {}
			public virtual void OnVariableTerminalFragment(ASTNode node) {}
			public virtual void OnVariableTerminalContext(ASTNode node) {}
			public virtual void OnVariableTerminalDefinition(ASTNode node) {}
			public virtual void OnVariableTerminalDifference(ASTNode node) {}
			public virtual void OnVariableTerminalSequence(ASTNode node) {}
			public virtual void OnVariableTerminalRepetition(ASTNode node) {}
			public virtual void OnVariableTerminalElement(ASTNode node) {}
			public virtual void OnVariableTerminalAtom(ASTNode node) {}
			public virtual void OnVariableTerminalRange(ASTNode node) {}
			public virtual void OnVariableTerminalText(ASTNode node) {}
			public virtual void OnVariableTerminalCardinalilty(ASTNode node) {}
			public virtual void OnVariableGrammarRules(ASTNode node) {}
			public virtual void OnVariableRule(ASTNode node) {}
			public virtual void OnVariableRuleSimple(ASTNode node) {}
			public virtual void OnVariableRuleTemplate(ASTNode node) {}
			public virtual void OnVariableRuleDefinition(ASTNode node) {}
			public virtual void OnVariableRuleAlternative(ASTNode node) {}
			public virtual void OnVariableRuleSequence(ASTNode node) {}
			public virtual void OnVariableRuleRepetition(ASTNode node) {}
			public virtual void OnVariableRuleTreeAction(ASTNode node) {}
			public virtual void OnVariableRuleElement(ASTNode node) {}
			public virtual void OnVariableRuleAtom(ASTNode node) {}
			public virtual void OnVariableRuleText(ASTNode node) {}
			public virtual void OnVariableRuleCardinality(ASTNode node) {}
			public virtual void OnVariableRuleContext(ASTNode node) {}
			public virtual void OnVariableRuleSub(ASTNode node) {}
			public virtual void OnVariableRuleAction(ASTNode node) {}
			public virtual void OnVariableRuleVirtual(ASTNode node) {}
			public virtual void OnVariableRuleRef(ASTNode node) {}
			public virtual void OnVariableRuleRefTemplate(ASTNode node) {}
			public virtual void OnVariableRuleArguments(ASTNode node) {}
			public virtual void OnVariableRuleParams(ASTNode node) {}
			public virtual void OnVirtualRange(ASTNode node) {}
		}

		/// <summary>
		/// Walk the AST using a visitor
		/// </summary>
		public static void Visit(ParseResult result, Visitor visitor)
		{
			VisitASTNode(result.Root, visitor);
		}

		/// <summary>
		/// Walk the AST using a visitor
		/// </summary>
		public static void VisitASTNode(ASTNode node, Visitor visitor)
		{
			for (int i = 0; i < node.Children.Count; i++)
				VisitASTNode(node.Children[i], visitor);
			switch(node.Symbol.ID)
			{
				case 0x0007: visitor.OnTerminalSeparator(node); break;
				case 0x0009: visitor.OnTerminalName(node); break;
				case 0x000A: visitor.OnTerminalInteger(node); break;
				case 0x000C: visitor.OnTerminalLiteralString(node); break;
				case 0x000D: visitor.OnTerminalLiteralAny(node); break;
				case 0x000E: visitor.OnTerminalLiteralText(node); break;
				case 0x000F: visitor.OnTerminalLiteralClass(node); break;
				case 0x0010: visitor.OnTerminalUnicodeBlock(node); break;
				case 0x0011: visitor.OnTerminalUnicodeCategory(node); break;
				case 0x0012: visitor.OnTerminalUnicodeCodepoint(node); break;
				case 0x0013: visitor.OnVariableFile(node); break;
				case 0x0014: visitor.OnVariableCfGrammar(node); break;
				case 0x0015: visitor.OnVariableGrammarOptions(node); break;
				case 0x0016: visitor.OnVariableOption(node); break;
				case 0x0017: visitor.OnVariableGrammarTerminals(node); break;
				case 0x0018: visitor.OnVariableTerminalItem(node); break;
				case 0x0019: visitor.OnVariableTerminalRule(node); break;
				case 0x001A: visitor.OnVariableTerminalFragment(node); break;
				case 0x001B: visitor.OnVariableTerminalContext(node); break;
				case 0x001C: visitor.OnVariableTerminalDefinition(node); break;
				case 0x001D: visitor.OnVariableTerminalDifference(node); break;
				case 0x001E: visitor.OnVariableTerminalSequence(node); break;
				case 0x001F: visitor.OnVariableTerminalRepetition(node); break;
				case 0x0020: visitor.OnVariableTerminalElement(node); break;
				case 0x0021: visitor.OnVariableTerminalAtom(node); break;
				case 0x0022: visitor.OnVariableTerminalRange(node); break;
				case 0x0023: visitor.OnVariableTerminalText(node); break;
				case 0x0024: visitor.OnVariableTerminalCardinalilty(node); break;
				case 0x0025: visitor.OnVariableGrammarRules(node); break;
				case 0x0026: visitor.OnVariableRule(node); break;
				case 0x0027: visitor.OnVariableRuleSimple(node); break;
				case 0x0028: visitor.OnVariableRuleTemplate(node); break;
				case 0x0029: visitor.OnVariableRuleDefinition(node); break;
				case 0x002A: visitor.OnVariableRuleAlternative(node); break;
				case 0x002B: visitor.OnVariableRuleSequence(node); break;
				case 0x002C: visitor.OnVariableRuleRepetition(node); break;
				case 0x002D: visitor.OnVariableRuleTreeAction(node); break;
				case 0x002E: visitor.OnVariableRuleElement(node); break;
				case 0x002F: visitor.OnVariableRuleAtom(node); break;
				case 0x0030: visitor.OnVariableRuleText(node); break;
				case 0x0031: visitor.OnVariableRuleCardinality(node); break;
				case 0x0032: visitor.OnVariableRuleContext(node); break;
				case 0x0033: visitor.OnVariableRuleSub(node); break;
				case 0x0034: visitor.OnVariableRuleAction(node); break;
				case 0x0035: visitor.OnVariableRuleVirtual(node); break;
				case 0x0036: visitor.OnVariableRuleRef(node); break;
				case 0x0037: visitor.OnVariableRuleRefTemplate(node); break;
				case 0x0038: visitor.OnVariableRuleArguments(node); break;
				case 0x0039: visitor.OnVariableRuleParams(node); break;
				case 0x0052: visitor.OnVirtualRange(node); break;
			}
		}
	}
}
