/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 3.4.0.0
 */
using System.Collections.Generic;
using Hime.Redist;
using Hime.Redist.Parsers;

namespace Lingu.Bootstrap.Hime
{
	/// <summary>
	/// Represents a parser
	/// </summary>
	public class LinguParser : LRkParser
	{
		/// <summary>
		/// The automaton for this parser
		/// </summary>
		private static readonly LRkAutomaton commonAutomaton = LRkAutomaton.Find(typeof(LinguParser), "LinguParser");
		/// <summary>
		/// Contains the constant IDs for the variables and virtuals in this parser
		/// </summary>
		public class ID
		{
			/// <summary>
			/// The unique identifier for variable file
			/// </summary>
			public const int VariableFile = 0x0015;
			/// <summary>
			/// The unique identifier for variable cf_grammar
			/// </summary>
			public const int VariableCfGrammar = 0x0016;
			/// <summary>
			/// The unique identifier for variable grammar_item
			/// </summary>
			public const int VariableGrammarItem = 0x0017;
			/// <summary>
			/// The unique identifier for variable grammar_options
			/// </summary>
			public const int VariableGrammarOptions = 0x0018;
			/// <summary>
			/// The unique identifier for variable option
			/// </summary>
			public const int VariableOption = 0x0019;
			/// <summary>
			/// The unique identifier for variable grammar_terminals
			/// </summary>
			public const int VariableGrammarTerminals = 0x001A;
			/// <summary>
			/// The unique identifier for variable terminal_rule
			/// </summary>
			public const int VariableTerminalRule = 0x001B;
			/// <summary>
			/// The unique identifier for variable terminal_expression
			/// </summary>
			public const int VariableTerminalExpression = 0x001C;
			/// <summary>
			/// The unique identifier for variable terminal_difference
			/// </summary>
			public const int VariableTerminalDifference = 0x001D;
			/// <summary>
			/// The unique identifier for variable terminal_sequence
			/// </summary>
			public const int VariableTerminalSequence = 0x001E;
			/// <summary>
			/// The unique identifier for variable terminal_repetition
			/// </summary>
			public const int VariableTerminalRepetition = 0x001F;
			/// <summary>
			/// The unique identifier for variable terminal_element
			/// </summary>
			public const int VariableTerminalElement = 0x0020;
			/// <summary>
			/// The unique identifier for variable terminal_not
			/// </summary>
			public const int VariableTerminalNot = 0x0021;
			/// <summary>
			/// The unique identifier for variable terminal_atom
			/// </summary>
			public const int VariableTerminalAtom = 0x0022;
			/// <summary>
			/// The unique identifier for variable range
			/// </summary>
			public const int VariableRange = 0x0023;
			/// <summary>
			/// The unique identifier for variable character
			/// </summary>
			public const int VariableCharacter = 0x0024;
			/// <summary>
			/// The unique identifier for variable text
			/// </summary>
			public const int VariableText = 0x0025;
			/// <summary>
			/// The unique identifier for variable terminal_cardinalilty
			/// </summary>
			public const int VariableTerminalCardinalilty = 0x0026;
			/// <summary>
			/// The unique identifier for variable grammar_rules
			/// </summary>
			public const int VariableGrammarRules = 0x0027;
			/// <summary>
			/// The unique identifier for variable rule
			/// </summary>
			public const int VariableRule = 0x0028;
			/// <summary>
			/// The unique identifier for variable rule_expression
			/// </summary>
			public const int VariableRuleExpression = 0x0029;
			/// <summary>
			/// The unique identifier for variable rule_alternative
			/// </summary>
			public const int VariableRuleAlternative = 0x002A;
			/// <summary>
			/// The unique identifier for variable rule_sequence
			/// </summary>
			public const int VariableRuleSequence = 0x002B;
			/// <summary>
			/// The unique identifier for variable rule_repetition
			/// </summary>
			public const int VariableRuleRepetition = 0x002C;
			/// <summary>
			/// The unique identifier for variable rule_drop_action
			/// </summary>
			public const int VariableRuleDropAction = 0x002D;
			/// <summary>
			/// The unique identifier for variable promote
			/// </summary>
			public const int VariablePromote = 0x002E;
			/// <summary>
			/// The unique identifier for variable drop
			/// </summary>
			public const int VariableDrop = 0x002F;
			/// <summary>
			/// The unique identifier for variable rule_element
			/// </summary>
			public const int VariableRuleElement = 0x0030;
			/// <summary>
			/// The unique identifier for variable rule_sub
			/// </summary>
			public const int VariableRuleSub = 0x0031;
			/// <summary>
			/// The unique identifier for variable rule_atom
			/// </summary>
			public const int VariableRuleAtom = 0x0032;
			/// <summary>
			/// The unique identifier for variable reference
			/// </summary>
			public const int VariableReference = 0x0033;
			/// <summary>
			/// The unique identifier for virtual range
			/// </summary>
			public const int VirtualRange = 0x004B;
		}
		/// <summary>
		/// The collection of variables matched by this parser
		/// </summary>
		/// <remarks>
		/// The variables are in an order consistent with the automaton,
		/// so that variable indices in the automaton can be used to retrieve the variables in this table
		/// </remarks>
		private static readonly Symbol[] variables = {
			new Symbol(0x0015, "file"), 
			new Symbol(0x0016, "cf_grammar"), 
			new Symbol(0x0017, "grammar_item"), 
			new Symbol(0x0018, "grammar_options"), 
			new Symbol(0x0019, "option"), 
			new Symbol(0x001A, "grammar_terminals"), 
			new Symbol(0x001B, "terminal_rule"), 
			new Symbol(0x001C, "terminal_expression"), 
			new Symbol(0x001D, "terminal_difference"), 
			new Symbol(0x001E, "terminal_sequence"), 
			new Symbol(0x001F, "terminal_repetition"), 
			new Symbol(0x0020, "terminal_element"), 
			new Symbol(0x0021, "terminal_not"), 
			new Symbol(0x0022, "terminal_atom"), 
			new Symbol(0x0023, "range"), 
			new Symbol(0x0024, "character"), 
			new Symbol(0x0025, "text"), 
			new Symbol(0x0026, "terminal_cardinalilty"), 
			new Symbol(0x0027, "grammar_rules"), 
			new Symbol(0x0028, "rule"), 
			new Symbol(0x0029, "rule_expression"), 
			new Symbol(0x002A, "rule_alternative"), 
			new Symbol(0x002B, "rule_sequence"), 
			new Symbol(0x002C, "rule_repetition"), 
			new Symbol(0x002D, "rule_drop_action"), 
			new Symbol(0x002E, "promote"), 
			new Symbol(0x002F, "drop"), 
			new Symbol(0x0030, "rule_element"), 
			new Symbol(0x0031, "rule_sub"), 
			new Symbol(0x0032, "rule_atom"), 
			new Symbol(0x0033, "reference"), 
			new Symbol(0x0036, "__V54"), 
			new Symbol(0x0039, "__V57"), 
			new Symbol(0x003D, "__V61"), 
			new Symbol(0x0041, "__V65"), 
			new Symbol(0x0043, "__V67"), 
			new Symbol(0x004E, "__V78"), 
			new Symbol(0x004F, "__V79"), 
			new Symbol(0x0050, "__V80"), 
			new Symbol(0x0052, "__VAxiom") };
		/// <summary>
		/// The collection of virtuals matched by this parser
		/// </summary>
		/// <remarks>
		/// The virtuals are in an order consistent with the automaton,
		/// so that virtual indices in the automaton can be used to retrieve the virtuals in this table
		/// </remarks>
		private static readonly Symbol[] virtuals = {
			new Symbol(0x004B, "range") };
		/// <summary>
		/// Initializes a new instance of the parser
		/// </summary>
		/// <param name="lexer">The input lexer</param>
		public LinguParser(LinguLexer lexer) : base (commonAutomaton, variables, virtuals, null, lexer) { }

		/// <summary>
		/// Visitor interface
		/// </summary>
		public class Visitor
		{
			public virtual void OnTerminalBlockComment(ASTNode node) {}
			public virtual void OnTerminalSeparator(ASTNode node) {}
			public virtual void OnTerminalName(ASTNode node) {}
			public virtual void OnTerminalInteger(ASTNode node) {}
			public virtual void OnTerminalLiteralAny(ASTNode node) {}
			public virtual void OnTerminalLiteralText(ASTNode node) {}
			public virtual void OnTerminalUnicodeBlock(ASTNode node) {}
			public virtual void OnTerminalUnicodeCategory(ASTNode node) {}
			public virtual void OnTerminalUnicodeCodepoint(ASTNode node) {}
			public virtual void OnVariableFile(ASTNode node) {}
			public virtual void OnVariableCfGrammar(ASTNode node) {}
			public virtual void OnVariableGrammarItem(ASTNode node) {}
			public virtual void OnVariableGrammarOptions(ASTNode node) {}
			public virtual void OnVariableOption(ASTNode node) {}
			public virtual void OnVariableGrammarTerminals(ASTNode node) {}
			public virtual void OnVariableTerminalRule(ASTNode node) {}
			public virtual void OnVariableTerminalExpression(ASTNode node) {}
			public virtual void OnVariableTerminalDifference(ASTNode node) {}
			public virtual void OnVariableTerminalSequence(ASTNode node) {}
			public virtual void OnVariableTerminalRepetition(ASTNode node) {}
			public virtual void OnVariableTerminalElement(ASTNode node) {}
			public virtual void OnVariableTerminalNot(ASTNode node) {}
			public virtual void OnVariableTerminalAtom(ASTNode node) {}
			public virtual void OnVariableRange(ASTNode node) {}
			public virtual void OnVariableCharacter(ASTNode node) {}
			public virtual void OnVariableText(ASTNode node) {}
			public virtual void OnVariableTerminalCardinalilty(ASTNode node) {}
			public virtual void OnVariableGrammarRules(ASTNode node) {}
			public virtual void OnVariableRule(ASTNode node) {}
			public virtual void OnVariableRuleExpression(ASTNode node) {}
			public virtual void OnVariableRuleAlternative(ASTNode node) {}
			public virtual void OnVariableRuleSequence(ASTNode node) {}
			public virtual void OnVariableRuleRepetition(ASTNode node) {}
			public virtual void OnVariableRuleDropAction(ASTNode node) {}
			public virtual void OnVariablePromote(ASTNode node) {}
			public virtual void OnVariableDrop(ASTNode node) {}
			public virtual void OnVariableRuleElement(ASTNode node) {}
			public virtual void OnVariableRuleSub(ASTNode node) {}
			public virtual void OnVariableRuleAtom(ASTNode node) {}
			public virtual void OnVariableReference(ASTNode node) {}
			public virtual void OnVirtualRange(ASTNode node) {}
		}

		/// <summary>
		/// Walk the AST using a visitor
		/// </summary>
		public static void Visit(ParseResult result, Visitor visitor)
		{
			VisitASTNode(result.Root, visitor);
		}

		/// <summary>
		/// Walk the AST using a visitor
		/// </summary>
		public static void VisitASTNode(ASTNode node, Visitor visitor)
		{
			for (int i = 0; i < node.Children.Count; i++)
				VisitASTNode(node.Children[i], visitor);
			switch(node.Symbol.ID)
			{
				case 0x0007: visitor.OnTerminalBlockComment(node); break;
				case 0x0008: visitor.OnTerminalSeparator(node); break;
				case 0x000D: visitor.OnTerminalName(node); break;
				case 0x000E: visitor.OnTerminalInteger(node); break;
				case 0x0010: visitor.OnTerminalLiteralAny(node); break;
				case 0x0011: visitor.OnTerminalLiteralText(node); break;
				case 0x0012: visitor.OnTerminalUnicodeBlock(node); break;
				case 0x0013: visitor.OnTerminalUnicodeCategory(node); break;
				case 0x0014: visitor.OnTerminalUnicodeCodepoint(node); break;
				case 0x0015: visitor.OnVariableFile(node); break;
				case 0x0016: visitor.OnVariableCfGrammar(node); break;
				case 0x0017: visitor.OnVariableGrammarItem(node); break;
				case 0x0018: visitor.OnVariableGrammarOptions(node); break;
				case 0x0019: visitor.OnVariableOption(node); break;
				case 0x001A: visitor.OnVariableGrammarTerminals(node); break;
				case 0x001B: visitor.OnVariableTerminalRule(node); break;
				case 0x001C: visitor.OnVariableTerminalExpression(node); break;
				case 0x001D: visitor.OnVariableTerminalDifference(node); break;
				case 0x001E: visitor.OnVariableTerminalSequence(node); break;
				case 0x001F: visitor.OnVariableTerminalRepetition(node); break;
				case 0x0020: visitor.OnVariableTerminalElement(node); break;
				case 0x0021: visitor.OnVariableTerminalNot(node); break;
				case 0x0022: visitor.OnVariableTerminalAtom(node); break;
				case 0x0023: visitor.OnVariableRange(node); break;
				case 0x0024: visitor.OnVariableCharacter(node); break;
				case 0x0025: visitor.OnVariableText(node); break;
				case 0x0026: visitor.OnVariableTerminalCardinalilty(node); break;
				case 0x0027: visitor.OnVariableGrammarRules(node); break;
				case 0x0028: visitor.OnVariableRule(node); break;
				case 0x0029: visitor.OnVariableRuleExpression(node); break;
				case 0x002A: visitor.OnVariableRuleAlternative(node); break;
				case 0x002B: visitor.OnVariableRuleSequence(node); break;
				case 0x002C: visitor.OnVariableRuleRepetition(node); break;
				case 0x002D: visitor.OnVariableRuleDropAction(node); break;
				case 0x002E: visitor.OnVariablePromote(node); break;
				case 0x002F: visitor.OnVariableDrop(node); break;
				case 0x0030: visitor.OnVariableRuleElement(node); break;
				case 0x0031: visitor.OnVariableRuleSub(node); break;
				case 0x0032: visitor.OnVariableRuleAtom(node); break;
				case 0x0033: visitor.OnVariableReference(node); break;
				case 0x004B: visitor.OnVirtualRange(node); break;
			}
		}
	}
}
